const state={token:sessionStorage.getItem('tessera_token'),current:null,health:null};
const $=id=>document.getElementById(id);
async function api(path,options={}){const headers={...(options.headers||{})};if(options.body)headers['Content-Type']='application/json';if(state.token)headers.Authorization=`Bearer ${state.token}`;const response=await fetch(path,{...options,headers});const data=await response.json().catch(()=>({error:'Invalid server response'}));if(response.status===401&&path!='/api/auth/login'){showLogin();throw new Error(data.error||'Authentication required')}if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2600)}
function showLogin(){$('loginDialog').showModal()}
function money(value){return new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'}).format(Number(value||0))}
async function refresh(){try{const health=await api('/api/health');state.health=health;$('healthDot').classList.add('ok');$('systemLabel').textContent=`${health.environment} · ledger ${health.ledger_valid?'verified':'invalid'}`;$('modeBadge').textContent=health.mode;$('killState').textContent=health.kill_switch?'FROZEN':'ACTIVE';$('killState').classList.toggle('safe',!health.kill_switch);$('killSwitchButton').textContent=health.kill_switch?'Resume execution':'Freeze execution';const [portfolio,runs,ledger,calls]=await Promise.all([api('/api/portfolio'),api('/api/runs'),api('/api/ledger'),api('/api/model-calls')]);renderMetrics(portfolio,runs.runs,ledger,calls.calls);renderPositions(portfolio.positions||[]);renderLedger(ledger.entries||[]);if(runs.runs.length){const selected=state.current&&runs.runs.find(x=>x.run_id===state.current.run_id);renderRun(selected||runs.runs[runs.runs.length-1])}}catch(error){if(!String(error.message).includes('Authentication'))toast(error.message)}}
function renderMetrics(portfolio,runs,ledger,calls){$('cashMetric').textContent=portfolio.cash===undefined?'Exchange':money(portfolio.cash);$('portfolioMode').textContent=portfolio.mode||state.health?.mode||'paper';$('runsMetric').textContent=runs.length;$('ledgerMetric').textContent=ledger.valid?'Verified':'Invalid';$('ledgerEntries').textContent=`${ledger.entries.length} chained entries`;$('callsMetric').textContent=calls.length}
function renderRun(run){state.current=run;$('runTitle').textContent=run.event.title;$('runSubtitle').textContent=`Severity ${Number(run.event.severity).toFixed(2)} · ${(run.event.symbols||[]).join(' / ')}`;$('runStatus').textContent=run.status;$('runStatus').dataset.status=run.status;$('runActions').classList.remove('hidden');$('approveButton').classList.toggle('hidden',!['AWAITING_APPROVAL','APPROVED'].includes(run.status));$('rejectButton').classList.toggle('hidden',run.status!=='AWAITING_APPROVAL');$('reconcileButton').classList.toggle('hidden',run.status!=='SUBMITTED');const confidence=Number(run.parliament?.confidence||0);$('confidenceBar').style.width=`${confidence*100}%`;$('confidenceValue').textContent=`${Math.round(confidence*100)}%`;$('riskDecision').textContent=(run.risk?.decision||'—').replaceAll('_',' ');$('agents').innerHTML=(run.agents||[]).map((agent,index)=>`<article class="agent"><span class="agent-index">${String(index+1).padStart(2,'0')}</span><div><h3>${escapeHtml(agent.agent.replaceAll('_',' '))}</h3><p>${escapeHtml(agent.finding)}</p></div><span class="badge">${Math.round(agent.confidence*100)}%</span></article>`).join('')||'No agent outputs.'}
function renderPositions(positions){$('positions').innerHTML=positions.length?positions.map(x=>`<div class="position"><div><strong>${escapeHtml(x.symbol)}</strong><br><span>${Number(x.quantity).toFixed(4)} units</span></div><span>${money(Number(x.quantity)*Number(x.avg_price))}</span></div>`).join(''):'No open positions.'}
function renderLedger(entries){$('ledgerFeed').innerHTML=entries.length?entries.slice(-12).reverse().map(x=>`<div class="ledger-item"><div><strong>${escapeHtml(x.entry_type.replaceAll('_',' '))}</strong><br><span>${escapeHtml(x.actor)}</span></div><span>${x.entry_hash.slice(0,8)}</span></div>`).join(''):'No ledger entries.'}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
async function runAction(action){if(!state.current)return;try{renderRun(await api(`/api/runs/${state.current.run_id}/${action}`,{method:'POST',body:'{}'}));toast(`${action} completed`);await refresh()}catch(error){toast(error.message)}}
$('newRunButton').onclick=()=>$('runDialog').showModal();document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>button.closest('dialog').close());$('runForm').severity.oninput=event=>$('severityOutput').textContent=Number(event.target.value).toFixed(2);
$('runForm').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.target);try{const run=await api('/api/runs',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({title:form.get('title'),severity:Number(form.get('severity')),symbols:String(form.get('symbols')).split(',').map(x=>x.trim()).filter(Boolean)})});$('runDialog').close();event.target.reset();renderRun(run);await refresh();toast('Parliament convened')}catch(error){toast(error.message)}};
$('approveButton').onclick=()=>runAction('approve');$('rejectButton').onclick=()=>runAction('reject');$('reconcileButton').onclick=()=>runAction('reconcile');$('replayButton').onclick=async()=>{if(!state.current)return;try{renderRun(await api('/api/replay',{method:'POST',body:JSON.stringify({run_id:state.current.run_id})}));await refresh();toast('Replay created')}catch(error){toast(error.message)}};
$('killSwitchButton').onclick=async()=>{const enable=!state.health?.kill_switch;if(!confirm(`${enable?'Freeze':'Resume'} all execution?`))return;try{await api('/api/risk/kill-switch',{method:'POST',body:JSON.stringify({enabled:enable,liquidate:false})});await refresh();toast(enable?'Execution frozen':'Execution resumed')}catch(error){toast(error.message)}};
$('loginForm').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.target);try{const result=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:form.get('username'),password:form.get('password')})});state.token=result.access_token;sessionStorage.setItem('tessera_token',state.token);$('loginError').textContent='';$('loginDialog').close();$('logoutButton').classList.remove('hidden');await refresh()}catch(error){$('loginError').textContent=error.message}};
$('logoutButton').onclick=()=>{state.token=null;sessionStorage.removeItem('tessera_token');showLogin()};
refresh();setInterval(refresh,15000);
